<a href="https://colab.research.google.com/github/DrAlexSanz/Data-Week-1-DNN/blob/master/Week_2_DNN_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import time
import numpy as np
import h5py
import matplotlib.pyplot as plt
import scipy
from PIL import Image
from scipy import ndimage
from lr_utils import load_dataset
from pandas import read_hdf
# from dnn_app_utils_v3 import *

%matplotlib inline
plt.rcParams['figure.figsize'] = (5.0, 4.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

%load_ext autoreload
%autoreload 2

np.random.seed(1)

print("Everything ok so far. This is encouraging.")

Everything ok so far. This is encouraging.


Now load data from Github. Because I have it there. Needs to be public.

In [0]:
# ! git clone https://github.com/DrAlexSanz/Data-Week-1-DNN.git

If this reading doesn't work, restart the run environment. Why? Because then it works.

In [10]:

with h5py.File("train_catvnoncat.h5") as train:
  train_x = np.array(train["train_set_x"][:]) # your train set features
  train_y = np.array(train["train_set_y"][:]) # your train set labels

#print(train_set_x_orig)

with h5py.File("test_catvnoncat.h5") as test:
  test_x = np.array(test["test_set_x"][:]) # your train set features
  test_y = np.array(test["test_set_y"][:]) # your train set labels

#print(test_x) #Prints to check




[[[[158 104  83]
   [161 106  85]
   [162 107  84]
   ...
   [170 120 100]
   [167 121 103]
   [172 127 109]]

  [[158 103  82]
   [160 104  82]
   [162 105  83]
   ...
   [169 118  99]
   [164 117  98]
   [168 121 104]]

  [[158 104  82]
   [161 105  82]
   [162 105  83]
   ...
   [173 123 102]
   [169 122 104]
   [168 122 104]]

  ...

  [[102  68  52]
   [ 44  31  23]
   [ 28  23  20]
   ...
   [163 118 102]
   [163 120 103]
   [166 121 105]]

  [[ 99  67  51]
   [ 38  28  22]
   [ 30  26  23]
   ...
   [161 117 100]
   [164 121 104]
   [168 123 106]]

  [[127  95  72]
   [ 39  29  22]
   [ 30  25  22]
   ...
   [165 122 105]
   [169 126 109]
   [173 128 110]]]


 [[[115 110 111]
   [137 129 129]
   [155 146 145]
   ...
   [159 156 157]
   [141 141 145]
   [121 122 127]]

  [[123 118 120]
   [143 136 136]
   [159 153 150]
   ...
   [167 164 165]
   [151 151 154]
   [130 133 137]]

  [[135 130 130]
   [150 145 141]
   [164 159 153]
   ...
   [173 174 172]
   [160 162 162]
   [141 144